#ifndef LPVC_VFW_RESOURCE_H
#define LPVC_VFW_RESOURCE_H


#define IDC_STATIC -1

// About dialog
#define IDD_ABOUT_DIALOG 100

// Config dialog
#define IDD_CONFIG_DIALOG 200

#define IDC_LPVC_IGNORE_KEY_FRAME_REQUESTS 201
#define IDC_LPVC_FORCE_KEY_FRAMES 202
#define IDC_LPVC_FORCE_KEY_FRAMES_INTERVAL 203
#define IDC_LPVC_USE_PALETTE 204

#define IDC_LPVC_ZSTD_WORKER_COUNT 210
#define IDC_LPVC_ZSTD_COMPRESSION_LEVEL_TEXT 211
#define IDC_LPVC_ZSTD_COMPRESSION_LEVEL_SLIDER 212


#endif // LPVC_VFW_RESOURCE_H
